# This files contains the settings of the blog

author: Maxime Marck
name: Maxime Marck
markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:title


future: false

# social media

# Github repositories
github_user: marckm
github_repo_url: https://github.com/marckm/marckm.github.io/

# Twitter
twitter_user: maximemarck
twitter_tweet_button: true

# configuration of pagination
paginate: 2
paginate_path: "/blog/page:num"